---
# tasks file for self-p-packageinstal
- name: install vim
  hosts: all
# connection: local
# gather_fatcs: false
  tasks:
   - name: install vim
     yum:
      name: vim
      state: present
     register: vim-installed
