---
# tasks file for self-p-packageinstal
- hosts: 192.168.1.192
  become: true
# connection: local
# gather_fatcs: false
  tasks:
   - name: install vim
     yum:
       name: vim
       state: absent